### ISSUE TITLE
regexifyString funtion is not preserving the line breaks in the string passed in as an input, its returning string by removing line breaks

### ISSUE THREAD

**Issue by nikithb** [kas-elvirov/regexify-string#5] opened 2021-07-03 19:24 UTC
Its not preserving the line breaks.

**Comment by artem-solovev** [comment] 2021-07-04 07:27
Please, provide reproducible example (as is, to be)

**Comment by artem-solovev** [comment] 2021-07-04 07:29
Till then i'm closing it. Reopen after adding proper description

**Comment by nikithb** [comment] 2021-07-04 08:25
`    function linkifyHash(str) {
        return regexifyString({
            pattern: /#[\w\u0590-\u05ff]+/g,
            decorator: (match, index) => <Link to={`/hashtag/${match.substr(1)}`} key={index} style={{ color: "#551a8b" }}>{match}</Link>,
            input: str,
        });
    }`

Have a look at above reproducible example and its not preserving the line breaks.

**Comment by artem-solovev** [comment] 2021-07-04 09:39
Not enough information
1. Place a link to reproducible example
2. Then describe what's wrong
3. Then describe desired behaviour

**Comment by nikithb** [comment] 2021-07-04 14:29
i am storing the text entered in textarea with line breaks and giving the same text as input to 'regexifyString' function, but 'regexifyString' function is not preserving those line breaks and its returning html with no line breaks.

For example if i am passing following text with line breaks -
"line1
line2
line3"
Its returning as following without preserving line breaks -
"line1line2line3"

```
function linkifyHash(str) { 
    return regexifyString({ 
       pattern: /#[\w\u0590-\u05ff]+/g, 
       decorator: (match, index) => <Link to={/hashtag/somehash} key={index}>{match}</Link>, 
       input: str 
    }); 
}

```

**Comment by artem-solovev** [comment] 2021-07-04 16:44
Interesting, i will check it in a few days. Thanks for report

**Comment by artem-solovev** [comment] 2021-07-04 16:45
I schedule this on next sunday. Have a good week man

**Comment by arunmir** [comment] 2021-08-06 03:06
Multiline input works perfectly fine for me. 
Try `white-space: pre-line;` style to <Link> node.

**Comment by artem-solovev** [comment] 2021-08-09 05:30
Hi guyz

Thank you for your report, I will check it by the end of the week and fix a.s.a.p
Have a good day)

**Comment by artem-solovev** [comment] 2021-08-25 15:53
Dear @nikithb check out branch I pushed i few minutes ago, please.
As i see it works as expected. If i missed something, let me know

**Comment by artem-solovev** [comment] 2021-08-25 16:11
Dear @nikithb hi.

Could you review [this PR](https://github.com/artem-solovev/regexify-string/pull/9)

If everything as you need we will release it then

**Comment by kas-elvirov** [comment] 2023-02-02 23:38
@arunmir @nikithb im closing this issue because of long silence on code-review

**Closed by kas-elvirov** 2023-02-02 23:38 UTC
Labels: bug, code review
